name: Download and Merge Tiles

on:
  workflow_dispatch
  
jobs:
  download-and-merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create output directory
      run: mkdir -p output
      
    - name: Download and merge tiles
      run: python download_and_merge_tiles.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: merged-tiles-${{ github.run_number }}
        path: output/
        retention-days: 30
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update merged tiles - $(date)"
          git push
        else
          echo "No changes to commit"
        fi

  deploy-pages:
    needs: download-and-merge
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Получаем последние изменения после коммита в предыдущем job
        fetch-depth: 0
        ref: ${{ github.ref_name }}
        
    - name: Pull latest changes
      run: git pull origin ${{ github.ref_name }}
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4