name: Remove _1 Suffix from Files

on:
  workflow_dispatch:

concurrency:
  group: wplace-tomsk-${{ github.ref }}
  cancel-in-progress: false

jobs:
  remove-suffix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Remove _1 suffix from files
      run: |
        cd output/20250813
        if [ -d "." ]; then
          echo "Processing files in output/20250813..."
          for file in *_1.*; do
            if [ -f "$file" ]; then
              newname=$(echo "$file" | sed 's/_1\././')
              echo "Renaming $file to $newname"
              mv "$file" "$newname"
            fi
          done
          echo "Suffix removal completed"
        else
          echo "Directory output/20250813 does not exist"
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        if ! git diff --staged --quiet; then
          git commit -m "Убран суффикс _1 у файлов в папке output/20250813"
          git push
        else
          echo "No changes to commit"
        fi
